server:
  port: 23000
  forward-headers-strategy: native # 使用了反向代理的情况下，内嵌tomcat要读取真正的请求header才能保证跳转正确
  servlet:
    session:
      cookie:
        name: GM-CART-SESSIONID
spring:
  cloud:
    nacos:
      discovery:
        server-addr: docker-serv:8848
  redis:
    host: docker-serv
    port: 6379
    password: abc123
    database: 1
  # 关闭thymeleaf缓存
  thymeleaf:
    cache: false

logging:
  level:
    daily.boot.gulimall.cart: debug

gulimall:
  feign:
    member: gulimall-member
    product: gulimall-product
  #自定义线程池参数
  threadpool:
    core-size: 10
    max-size: 30
    max-queue: 150
    keepalive-time: 20 # 最大等待时间，单位为秒
  # 单点登录登出配置
  sso:
    auth-server: http://auth.gulimall.com
    request-matchers: /**
    auth-request-matchers: /**/user/**
    logout-url: /user/logout
  #购物车配置项
  cart:
    user-key-cookie-name: user-key
    user-key-cookie-max-age: 2592000 #1个月



security:
  oauth2:
    #OAuth2 Client配置，对应OAuth2ClientProperties类
    client:
      client-id: gulimall-cart
      client-secret: abc123
      user-authorization-uri: ${gulimall.sso.auth-server}/oauth/authorize # 获取用户的授权码地址
      access-token-uri: ${gulimall.sso.auth-server}/oauth/token # 获取访问令牌的地址
      use-current-uri: false
      pre-established-redirect-uri: http://cart.gulimall.com/user/login
    # OAuth2 Resource 配置，对应 ResourceServerProperties 类
    resource:
      token-info-uri: ${gulimall.sso.auth-server}/oauth/check_token # 校验访问令牌是否有效的地址

    sso:
      login-path: /user/login  #自定义登录url


feign:
  client:
    config:
      default:
        connect-timeout: 60000
        read-timeout: 60000

