server:
  port: 21000
  forward-headers-strategy: native # 使用了反向代理的情况下，内嵌tomcat要读取真正的请求header才能保证跳转正确
  servlet:
    session:
      cookie:
        name: GM-SEARCH-SESSIONID
spring:
  cloud:
    nacos:
      discovery:
        server-addr: docker-serv:8848
  elasticsearch:
    rest:
      uris:
        - http://docker-serv:9200
  # 关闭thymeleaf缓存
  thymeleaf:
    cache: false

logging:
  level:
    daily.boot.gulimall.search: debug

gulimall:
  search:
    es:
      map-underscore-to-camel-case: true
      index-underline: true
      index:
        number-of-shards: 1
        number-of-replicas: 0-1
        auto-expand-replicas: true
      doc-location:
        - daily.boot.gulimall.search
  # 单点登录登出配置
  sso:
    auth-server: http://auth.gulimall.com
    request-matchers: /user/**
    logout-url: /user/logout

security:
  oauth2:
    #OAuth2 Client配置，对应OAuth2ClientProperties类
    client:
      client-id: gulimall_search
      client-secret: abc123
      user-authorization-uri: ${gulimall.sso.auth-server}/oauth/authorize # 获取用户的授权码地址
      access-token-uri: ${gulimall.sso.auth-server}/oauth/token # 获取访问令牌的地址
      use-current-uri: false
      pre-established-redirect-uri: http://search.gulimall.com/user/login
    # OAuth2 Resource 配置，对应 ResourceServerProperties 类
    resource:
      token-info-uri: ${gulimall.sso.auth-server}/oauth/check_token # 校验访问令牌是否有效的地址

    sso:
      login-path: /user/login  #自定义登录url




