server:
  port: 20000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: docker-serv:8848

logging:
  level:
    daily.boot.gulimall.thirdparty: debug

gulimall:
  httpclient:
    max-per-route: 25
    max-total: 50
    socket-timeout: 1500
    connect-timeout: 1500
    connect-request-timeout: 1000
